version: 2
jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git
    working_directory: /root/work
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          TAG=1.0.$CIRCLE_BUILD_NUM
          docker build -t bksaville/build-ionic:$TAG .
          docker build -t bksaville/build-ionic:latest .
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push bksaville/build-ionic:$TAG
          docker push bksaville/build-ionic:latest